§quizType
choice

§quizBalls
4

§quizQuestion
What will be logged in console if the call funcs.second() will end with calling reject?



§quizJS
const promise = function (name) {
  const time = Math.round(Math.random() * 4000)
  return new Promise((resolve, reject) => Math.random() < 0.2
    ? reject(`Rejected: ${name}`)
    : setTimeout(() => resolve(`Resolved: ${name}`), time))
}

const funcs = ['first', 'second', 'third']
  .map(name => () => promise(name))

const getResult = async () => await Promise
  .all(funcs.map(func => func().catch(err => console.warn(err))))

console.log(getResult().then(response => console.log(response)))




§choiceVariants
Warning 'Rejected: first'
Warning 'Rejected: second'
Warning 'Rejected: third'
Message 'Resolved: first'
Message 'Resolved: second'
Message 'Resolved: third'
Array ['Resolved: first', undefined, undefined]
Array ['Resolved: first', undefined, 'Resolved: third']
Array ['Resolved: first', Resolved: second, 'Resolved: third']


§rightChoice
1,7
