§quizType
choice

§quizBalls
4

§quizQuestion
What will be logged in console if the call funcs.second() will end with calling reject?



§quizJS
const promise = function (name) {
  const time = Math.round(Math.random() * 8000)
  return new Promise(function (resolve, reject) {
    Math.random() < 0.5
      ? reject(`Rejected: ${name}`)
      : setTimeout(function () { resolve(`Resolved: ${name}`) }, time)
  })
}

function createFunction (name) {
  return function () {
    return promise(name)
  }
}

const funcs = { first: null, second: null, third: null }
for (const name in funcs) {
  funcs[name] = createFunction(name)
}

async function getResult () {
  for (const funcName of ['first', 'second', 'third']) {
    console.log(await funcs[funcName]())
  }
}

getResult().catch(err => console.warn(err))



§choiceVariants
Resolved: first
Resolved: second
Resolved: third
Rejected: first
Rejected: second
Rejected: third


§rightChoice
0,4
