§quizType
findError

§quizBalls
7

§quizQuestion
Вставьте вместо ••• правильные выражения



wrongContent
let promise = function ( name ) {
    return new Promise (
        function ( resolve, reject ) {
            Math.random() < 0.5 ? ••• ( `Rejected: ${name}` ) :
                setTimeout (
                    function () {
                        ••• ( `Resolved: ${name}` )
                    },
                    Math.round ( Math.random() * 8000 )
                )
        }
    )
}

function createFunction ( name ) {
    return function () {
        return promise ( name )
    }
}
let funcs = { first: null, second: null, third: null }
for ( let name in funcs ) {
    funcs [ name ] = createFunction ( name )
}

funcs.first()
    .••• ( res => console.log ( res ) )
    .catch ( err => console.warn ( err ) )
funcs.second()
    .••• ( res => console.log ( res ) )
    .catch ( err => console.warn ( err ) )
funcs.third()
    .••• ( res => console.log ( res ) )
    .catch ( err => console.warn ( err ) )

§rightContent
let promise = function ( name ) {
    return new Promise (
        function ( resolve, reject ) {
            Math.random() < 0.5 ? reject ( `Rejected: ${name}` ) :
                setTimeout (
                    function () {
                        resolve( `Resolved: ${name}` )
                    },
                    Math.round ( Math.random() * 8000 )
                )
        }
    )
}

function createFunction ( name ) {
    return function () {
        return promise ( name )
    }
}
let funcs = { first: null, second: null, third: null }
for ( let name in funcs ) {
    funcs [ name ] = createFunction ( name )
}

funcs.first()
    .then ( res => console.log ( res ) )
    .catch ( err => console.warn ( err ) )
funcs.second()
    .then ( res => console.log ( res ) )
    .catch ( err => console.warn ( err ) )
funcs.third()
    .then ( res => console.log ( res ) )
    .catch ( err => console.warn ( err ) )
